import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
/* Images */
import Image from 'next/image'
import Waves1 from '../public/img/landing/wave1.svg'
import Logo from '../public/img/landing/nutzen_logo.png'

/* CSS */
import styles from '../styles/Recetas.module.css'

/* Components */
import Header from '../components/Header'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Header */}
        <Header />

        {/* landing */}
        {/* wave */}
        <div className={styles.waves__container1}>
          <Image className={styles.wave1} src={Waves1} alt=""/>
        </div>

        {/* background image */}
        <div className={styles.title__container}>
            <h1 className={styles.title}>Prueba nuestras deliciosas recetas</h1>
        </div>

        {/* Filters */}
        <div className={styles.filters__container}>
            <div className={styles.filters__inner__container}>
                <div className={styles.filter__item}>
                    <p>Desayunos</p>
                </div>
                <div className={styles.filter__item}>
                    <p>Snacks</p>
                </div>
                <div className={styles.filter__item}>
                    <p>Postres</p>
                </div>
                <div className={styles.filter__item}>
                    <p>Pasteles y panques</p>
                </div>
            </div>
        </div>

        <div className={styles.recetas__container}>
            <div className={styles.recetas__inner__container}>
                <div className={styles.receta__container}>
                    <div className={styles.receta__img}></div>
                    <h4>Título de receta</h4>
                    <button>Ver receta</button>
                </div>
                <div className={styles.receta__container}>
                    <div className={styles.receta__img}></div>
                    <h4>Título de receta</h4>
                    <button>Ver receta</button>
                </div>
                <div className={styles.receta__container}>
                    <div className={styles.receta__img}></div>
                    <h4>Título de receta</h4>
                    <button>Ver receta</button>
                </div>
                <div className={styles.receta__container}>
                    <div className={styles.receta__img}></div>
                    <h4>Título de receta</h4>
                    <button>Ver receta</button>
                </div>
            </div>
        </div>

        {/* Footer */}
        <Footer />

      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}

export default Home
